import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";
import { PAIRS } from "@/lib/forex-data";
import { CheckCircle2 } from "lucide-react";

export const Route = createFileRoute("/signals")({
  head: () => ({ meta: [{ title: "Signals — KTM Tech Forex" }] }),
  component: Signals,
});

function Signals() {
  return (
    <AppShell title="Trade Signals" subtitle="Generated by the AI Consensus Engine.">
      <div className="space-y-4">
        {PAIRS.map((p) => {
          const rr = ((Math.abs(p.takeProfit - p.entry)) / (Math.abs(p.entry - p.stopLoss))).toFixed(2);
          return (
            <div key={p.symbol} className="glass rounded-2xl p-6">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div>
                  <div className="font-mono font-bold text-xl">{p.symbol}</div>
                  <div className="text-xs text-muted-foreground">{p.name}</div>
                </div>
                <div className="flex items-center gap-4">
                  <span className={`text-sm font-bold px-3 py-1.5 rounded-md ${
                    p.signal === "BUY" ? "bg-success/20 text-success" :
                    p.signal === "SELL" ? "bg-destructive/20 text-destructive" :
                    "bg-muted text-muted-foreground"
                  }`}>{p.signal}</span>
                  <div className="text-right">
                    <div className="text-xs text-muted-foreground">Confidence</div>
                    <div className="font-bold text-primary">{p.confidence}%</div>
                  </div>
                </div>
              </div>
              <div className="mt-5 grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                <Stat label="Entry" value={p.entry} />
                <Stat label="Take Profit" value={p.takeProfit} className="text-success" />
                <Stat label="Stop Loss" value={p.stopLoss} className="text-destructive" />
                <Stat label="Risk:Reward" value={`1 : ${rr}`} />
              </div>
              <ul className="mt-5 grid sm:grid-cols-2 gap-2 text-sm">
                {p.reasons.map((r) => (
                  <li key={r} className="flex items-center gap-2 text-muted-foreground">
                    <CheckCircle2 className="h-4 w-4 text-primary shrink-0" />{r}
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
    </AppShell>
  );
}

function Stat({ label, value, className = "" }: { label: string; value: string | number; className?: string }) {
  return (
    <div className="rounded-lg bg-background/50 p-3">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className={`font-mono font-semibold mt-0.5 ${className}`}>{value}</div>
    </div>
  );
}